name: ipypdf

channels:
  - https://conda.anaconda.org/conda-forge

dependencies:
  - pip
  - poppler # needed for pdf.info
  - pdf2image
  - pytesseract
  - tesseract
  - spacy
  - spacy-model-en_core_web_sm
  - jupyterlab
  - ipycanvas
  - ipycytoscape
  - ipyevents
  - ipywidgets
  - pandas
  - numpy <=1.19.3,>=1.13
  - pip:
    - layoutparser
    - layoutparser[paddledetection]