name: dev

channels:
  - conda-forge
  - pytorch

dependencies:
  - numpy
  - pandas
  - pip
  - python

  # UI
  - ipycanvas =0.13.1
  - ipycytoscape
  - ipyevents
  - ipywidgets
  - jupyterlab

  # NLP
  - spacy =3.2.2
  - spacy-model-en_core_web_sm
  - scipy

  # OCR
  - tesseract
  - pytesseract =0.3.10
  
  # opencv-python
  - py-opencv =4.5.5
  - libopencv
  - opencv
  
  # pdf utils
  - pillow  # paddlepaddle uses deprecated pillow functions
  - poppler # needed for pdf.info
  - pdf2image
  
  - detectron2
  - pytorch
  # - mesa-libgl-cos7-aarch64 # many virtual machines do not ship with libg1
  # (WSL only) echo "nameserver 8.8.8.8" | sudo tee /etc/resolv.conf > /dev/null
  # sudo apt-get install libgl1 --fix-missing

  - pip:
    - layoutparser

  # Tests
  - pytest
  - pytest-cov