{% set version = "0.5.6" %}

package:
  name: wand
  version: {{ version }}

source:
  url: https://github.com/emcconville/wand/releases/download/{{ version }}/Wand-{{ version }}.tar.gz


build:
  number: 0
  noarch: python
  script: python -m pip install . --no-deps
requirements:
  host:
    - python =3.8
    - pip
