{% set data = load_setup_py_data() %}

package:
  name: ipypdf
  version: {{ data['version'] }}

source: # url to recipe or repo
  git_url: https://github.com/joelstansbury/ipypdf.git
  git_depth: 1 # (only need the latest)

build:
  script: {{ PYTHON }} -m pip install -vv .
  noarch: python
  
  entry_points:
    {% for entry in data['entry_points']['console_scripts'] %}
      - {{ entry.split('=')[0].strip() }} = {{ entry.split('=')[1].strip() }}
    {% endfor %}
  

requirements:
  host:
    - python
    - pip
    - setuptools
  run:
    - python
    - pywin32 # [win]
    - ipycanvas
    - ipycytoscape
    - ipyevents
    - ipytree
    - ipywidgets
    - jupyterlab  >=3.0
    - numpy       <=1.19.3,>=1.13 # Constrained by paddlepaddle
    - opencv      <=4.5.5
    - pandas      <=1.3.5
    - pdf2image   <=1.16.0
    - poppler
    - pytesseract
    - spacy
    - spacy-model-en_core_web_lg
    - tesseract
    - traitlets

test:
  source_files:
    - tests
  requires:
    - pytest
    - pytest-cov
  commands:
    - pytest
  imports:
    - ipypdf

about:
  home: https://github.com/JoelStansbury/ipypdf
  summary: Jupyter widget for applying nlp to pdf documents
  license: {{ data.get('license') }}
  license_file: LICENSE
